### ISSUE TITLE
 roslaunch robot_sim_demo robot_spawn.launch 显示问题

### ISSUE THREAD

**Issue by xiaoerlaigeid** [sychaichangkun/ROS-Academy-for-Beginners#39]
`yzk@yzk-Lenovo-Product:~/catkin_ws/src$ roslaunch robot_sim_demo robot_spawn.launch 
... logging to /home/yzk/.ros/log/e16ecaf6-341b-11e8-b944-f80f41de0ba6/roslaunch-yzk-Lenovo-Product-8841.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
xacro.py is deprecated; please use xacro instead
`

**Comment by xiaoerlaigeid** [comment]
请问这个问题如何解决

**Comment by sychaichangkun** [comment]
你好，这是个warning，原因是robot_description参数加载的时候用的是老的写法xacro.py而不是xacro。
这是个warning，不会影响使用，我会把这个改过来。
