### ISSUE TITLE
 error:

### ISSUE THREAD

**Issue by YuanxinXing** [sychaichangkun/ROS-Academy-for-Beginners#40]
[gazebo-2] process has died [pid 15867, exit code 255, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/egbert/catkin_ws/src/ROS-Academy-for-Beginners/robot_sim_demo/worlds/ROS-Academy.world __name:=gazebo __log:=/home/egbert/.ros/log/dc3d7d62-38ac-11e8-b37c-64fb816eab88/gazebo-2.log].
log file: /home/egbert/.ros/log/dc3d7d62-38ac-11e8-b37c-64fb816eab88/gazebo-2*.log
libGL error: failed to create drawable

您好，请问我在运行robot_sim_demo时出现这个问题是怎么回事呢？求解，谢谢您。顺便问一下您该怎么样解决呢？

**Comment by DavidHan008** [comment]
安装gazebo7了吗？

**Comment by sychaichangkun** [comment]
看看这个回答
https://answers.ros.org/question/286985/libgl-error-failed-to-create-drawable/
