### ISSUE TITLE
在indigo 版本运行出错.

### ISSUE THREAD

**Issue by hitxiaomi** [sychaichangkun/ROS-Academy-for-Beginners#41]
![_020](https://user-images.githubusercontent.com/28753180/38410244-aa1bea98-39b6-11e8-8479-0623d9aaa19e.png)

**Comment by DavidHan008** [comment]
安装gazbo7了吗？

**Comment by hitxiaomi** [comment]
indigo 默认的是安装gazebo2，尝试了一下在indigo上安装gazebo，按照博客的方法https://blog.csdn.net/tust123qht/article/details/78796617，还是没有成功。
