### ISSUE TITLE
与orb2slam的对接

### ISSUE THREAD

**Issue by YuYuCong** [sychaichangkun/ROS-Academy-for-Beginners#45]
在运行launch时找不到RGBD节点
![2018-04-26 19-44-15](https://user-images.githubusercontent.com/30014869/39303932-84b41b98-498a-11e8-9260-80c149637f18.png)

确认已经添加了pkg的路径，以下是~/.bashrc的部分内容
![2018-04-26 19-45-10](https://user-images.githubusercontent.com/30014869/39303919-7c43096a-498a-11e8-8f6f-c8d8e87e575b.png)

**Comment by YuYuCong** [comment]
QUESTION

**Comment by sychaichangkun** [comment]
确定编译过ORB_SLAM2的ROS版吗？
可以看看ORB_SLAM2/Examples/ROS/ORB_SLAM2里有没有RGBD，Mono, Stereo这些二进制文件
如果有的话可能是.bashrc里的ROS_PACKAGE_PATH环境变量没有加上

**Comment by YuYuCong** [comment]
检查了ORB_SLAM2/Examples/ROS/ORB_SLAM2里面确实没有RGBD，Mono, Stereo这些二进制文件。
然后我记起来./build_ros.sh编译的时候有报错信息：
请问以下报错您是否已有解决方案？
![2018-04-30 08-39-58](https://user-images.githubusercontent.com/30014869/39412632-1b955814-4c52-11e8-8bdf-ebd1111ef5ed.png)

**Comment by sychaichangkun** [comment]
应该是没有链接boost，看看这个
[https://stackoverflow.com/questions/25864797/error-adding-symbols-dso-missing-from-command-line](url)

**Comment by YuYuCong** [comment]
非常感谢！问题已经得到了解决！
#问题描述：
编译./build_ros.sh时报错：
/usr/lib/x86_64-linux-gnu/libboost_system.so: error adding symbols: DSO missing from command line
#解决方案：
在ORB_SLAM2/Examples/ROS/ORB_SLAM2/Cmakelist.txt 文件后面加入两句：
target_link_libraries(Stereo boost_system boost_filesystem)  
target_link_libraries(RGBD boost_system boost_filesystem)  
保存后再次编译即可。
