### ISSUE TITLE
在rviz中无法看到激光雷达的红线

### ISSUE THREAD

**Issue by shenhao2954988368** [sychaichangkun/ROS-Academy-for-Beginners#48]
运行了仿真环境后，打开rviz，在rviz中添加雷达的节点信息/scan，但在地图上不显示激光雷达扫出来的红线，问一下是什么原因导致的，希望哪位老师能为我解惑

**Comment by sychaichangkun** [comment]
这个问题经常出在Gazebo的laser插件上，教程里默认是用GPU版本的laser插件(libgazebo_ros_gpu_laser.so)
换成cpu版本的(libgazebo_ros_laser.so)试试

方法：找到sick_tim.urdf.xacro，用line77,line99替换上面一行
