### ISSUE TITLE
请问在开发的过程中是怎么知道需要依赖这些依赖项？

### ISSUE THREAD

**Issue by zjlooojoe** [sychaichangkun/ROS-Academy-for-Beginners#49]
在第二步中，安装教学包所需的依赖

$ cd ~/catkin_ws
$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
上面这一句依赖项的安装不太能理解，不明白系统为什么能够自动识别要安装的这些依赖。

**Comment by lazyparser** [comment]
--from-paths src

是不是表示去src目录下找package.xml？ package.xml 中包含了各种 depends，一个一个安装就行了。

**Comment by zjlooojoe** [comment]
那这里的src如果有多个工作空间呢？不单单是这个教程所给出的功能包，那是不是从.bashrc上的路径都寻找package.xml？那显然不现实吧

**Comment by lazyparser** [comment]
src 的上层目录是 catkin 的空间。我想你说的是 packages？如果是指 packages，我理解是的，遍历。

**Comment by zjlooojoe** [comment]
那这里的path应当指的是.bachrc中source的地址吧？如果是的话那意味着整个跟ros相关的都进行安装？因为我的.bashrc是这样的
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash 
source ~/ROS_academy/devel/setup.bash

**Comment by zjlooojoe** [comment]
喔，明白了，不好意思哈，这里的path应该就是上面的那步，cd到工作空间，然后安装此工作空间所需要的所有依赖项

**Comment by zjlooojoe** [comment]
谢谢谢谢
