### ISSUE TITLE
运行roslaunch robot_sim_demo robot_spawn.launch报错

### ISSUE THREAD

**Issue by Rashfu** [sychaichangkun/ROS-Academy-for-Beginners#51]
两个gazebo的结点进程报错
[gazebo-2] process has died [pid 13326, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/zjy/catkin_ws/src/ROS-Academy-for-Beginners/robot_sim_demo/worlds/ROS-Academy.world __name:=gazebo __log:=/home/zjy/.ros/log/2fceccea-a15f-11e8-aa76-000c292c33ab/gazebo-2.log].
以及
[gazebo_gui-3] process has died [pid 13330, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/zjy/.ros/log/2fceccea-a15f-11e8-aa76-000c292c33ab/gazebo_gui-3.log].
不知道该怎么处理。我的gazebo更新之后直接是7.14.0版本

**Comment by lazyparser** [comment]
后续问题可以去 https://q.droid.ac.cn 上问，人多一些；需要邀请，可以给论坛置顶链接中的老师发邮件。

**Comment by Rashfu** [comment]
谢谢您老师~

**Comment by Rashfu** [comment]
老师，论坛置顶中写着联系罗校长，后面的给网址打不开。
