### ISSUE TITLE
请问大家有没有遇到过这个问题？？？卡在这儿挺长时间了

### ISSUE THREAD

**Issue by CharmingYoona** [sychaichangkun/ROS-Academy-for-Beginners#52]
Could not find a package configuration file provided by "move_base" with
  any of the following names:

    move_baseConfig.cmake
    move_base-config.cmake

  Add the installation prefix of "move_base" to CMAKE_PREFIX_PATH or set
  "move_base_DIR" to a directory containing one of the above files.  If
  "move_base" provides a separate development package or SDK, be sure it has
  been installed.
明明我在build文件夹下能找到这个文件啊

**Comment by sychaichangkun** [comment]
sudo apt install ros-kinetic-move-base

**Comment by lazyparser** [comment]
缺少依赖关系。按照上面的方式安装对应的依赖。

**Comment by Ethan-BIG** [comment]
roslaunch robot_sim_demo robot_spawn.launch，在开启这个launch的时候加载到一半博物馆的界面就退出了，有没有人遇到过这个问题  ._.

[ INFO] [1547432612.702435149, 0.607000000]: Physics dynamic reconfigure ready.
[ INFO] [1547432612.966893481, 0.843000000]: Physics dynamic reconfigure ready.
[cmd_vel_mux-8] process has finished cleanly
log file: /home/python/.ros/log/449d3296-17a3-11e9-bbd0-f82fa8bd9eaf/cmd_vel_mux-8*.log
Killed
[gazebo_gui-3] process has died [pid 5675, exit code 137, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/python/.ros/log/449d3296-17a3-11e9-bbd0-f82fa8bd9eaf/gazebo_gui-3.log].
log file: /home/python/.ros/log/449d3296-17a3-11e9-bbd0-f82fa8bd9eaf/gazebo_gui-3*.log
