### ISSUE TITLE
gazebo的问题

### ISSUE THREAD

**Issue by benbenji** [sychaichangkun/ROS-Academy-for-Beginners#53]
您好 [我在运行robot_sim_demo时候，发现整个博物馆和机器人的一些部分显示不出来，如图[](url)](url)

>
![test](https://user-images.githubusercontent.com/2499988/45533850-9d7b2d00-b82b-11e8-958a-a35c8095d622.jpg)
进一步发现在工作空间里自己定义的mesh文件家里的dae文件加载不出来，而官方自带的模块却可以，请问您遇到过类似的情况吗？我用的是ubuntu18.04 他的gazebo是9.0版本，谢谢！

**Comment by lazyparser** [comment]
从命令行或者log文件里面有没有提示有文件加载错误之类的信息？

另外欢迎去q站提问，后续顾问都在q站了。 https://q.droid.ac.cn

邀请制，请按照置顶中的联系方式联系罗校长加入q站

**Comment by YCH188** [comment]
请问这个问题解决了吗？

**Comment by YCH188** [comment]
@benbenji
