### ISSUE TITLE
运行 roslaunch robot_sim_demo robot_spawn.launch报错，请问大家有遇到过的吗？

### ISSUE THREAD

**Issue by cdlwhm1217096231** [sychaichangkun/ROS-Academy-for-Beginners#55]
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/xacro/xacro.py", line 55, in <module>
    import xacro
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/xacro/__init__.py", line 35, in <module>
    import glob
  File "/home/cdl/software/anaconda3/lib/python3.5/glob.py", line 4, in <module>
    import re
ImportError: No module named 're'
while processing /home/cdl/tutorial_ws/src/ROS-Academy-for-Beginners/robot_sim_demo/launch/include/xbot-u.launch.xml:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/share/xacro/xacro.py /home/cdl/tutorial_ws/src/ROS-Academy-for-Beginners/robot_sim_demo/urdf/robot.xacro] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py $(find robot_sim_demo)/urdf/robot.xacro" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by lazyparser** [comment]
这个主要原因是 python 环境混淆了。仔细看路径， python2 和 python3 混合了。

可以去 https://q.droid.ac.cn 上申请个账号去那里问，那里人多

**Comment by cdlwhm1217096231** [comment]
我发现py2和py3在环境变量设置中~/.bashrc不能同时设置，只能把环境变量中的anaconda3的路径给注释掉。ROS才能运行正常，就是比较麻烦一点。

**Comment by cdlwhm1217096231** [comment]
我发现py2和py3在环境变量设置中~/.bashrc不能同时设置，只能把环境变量中的anaconda3的路径给注释掉。ROS才能运行正常，就是比较麻烦一点。

**Comment by cdlwhm1217096231** [comment]
@lazyparser 
 我发现py2和py3在环境变量设置中~/.bashrc不能同时设置，只能把环境变量中的anaconda3的路径给注释掉。ROS才能运行正常，就是比较麻烦一点。

**Comment by lazyparser** [comment]
是的，ROS的很多问题都是 anaconda3 的霸道导致的。

**Comment by gouyiyong** [comment]
我也遇到这个问题，具体还不知道怎么办，你解决了吗？

**Comment by AiWangZhenPing** [comment]
请问最终是怎么解决的呢？

**Comment by AiWangZhenPing** [comment]
> 我也遇到这个问题，具体还不知道怎么办，你解决了吗？

请问解决了么？

**Comment by cdlwhm1217096231** [comment]
请把环境变量中的PATH中的anaconda中的python3的解释器注释掉,ROS中默认使用的是python2解释器。
gedit ~/.bashrc
修改PATH环境变量
source ~/.bashrc
