### ISSUE TITLE
Model地图场景

### ISSUE THREAD

**Issue by wy2275** [sychaichangkun/ROS-Academy-for-Beginners#56]
首先感谢教程以及源码分享。。。
我想问下仿真里面的model是直接改源码生成，比如地面纹理，还是通过其他方法导入。我现在做自动驾驶的模拟，需要在ground上加车道线。

谢谢

**Comment by sychaichangkun** [comment]
gazebo支持加入车道线，你可以画一些贴图贴上去

**Comment by wy2275** [comment]
请问是用model建路面然后贴图进去吗，我看教程里面是用Blender做的。
