### ISSUE TITLE
Invoking "cmake" failed

### ISSUE THREAD

**Issue by SailorLou** [sychaichangkun/ROS-Academy-for-Beginners#57]
您好，我在按照步骤安装这个教学包的时候，出现了如下错误：可否帮我看以下，非常感谢
-- +++ processing catkin package: 'navigation_sim_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/navigation_sim_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find move_base (missing: move_base_DIR)
-- Could not find the required component 'move_base'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "move_base" with
  any of the following names:

    move_baseConfig.cmake
    move_base-config.cmake

  Add the installation prefix of "move_base" to CMAKE_PREFIX_PATH or set
  "move_base_DIR" to a directory containing one of the above files.  If
  "move_base" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ROS-Academy-for-Beginners/navigation_sim_demo/CMakeLists.txt:3 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/sailor/works/ros/tutorial_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/sailor/works/ros/tutorial_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by YukunXia** [comment]
sudo apt-get install ros-kinetic-controller-manager
sudo apt-get install ros-kinetic-navigation
cd your_work_space/src
git clone https://github.com/ros-perception/slam_gmapping.git
git clone https://github.com/ros-perception/openslam_gmapping.git
cd ..
rosdep install --from-paths src --ignore-src

--------------------- 
后半部分参考了：https://blog.csdn.net/qq_32115419/article/details/81585942
