### ISSUE TITLE
rosrun没有robot_sim_demo

### ISSUE THREAD

**Issue by zhudaoruyi** [sychaichangkun/ROS-Academy-for-Beginners#58]
想用键盘控制robot的运动，按照步骤都安装编译成功，但用rosrun并没有robot_sim_demo
如下安装成功的提示：
```bash
ubuntu@ubuntu:~/catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
#All required rosdeps installed successfully
```

**Comment by Hankfirst** [comment]
roslaunch robot_sim_demo 能找到吗？

**Comment by chrisenew** [comment]
我也是运行时提示没有找到这个package，请问有人知道怎么回事吗？

**Comment by sychaichangkun** [comment]
1.rosrun之前确定已经source了.bashrc
2.确定robot_sim_demo已经被编译，可在devel/lib下面找找
或者rospack find robot_sim_demo
