### ISSUE TITLE
安装依赖时出错，系统版本ubuntu 18.04，ros版本melodic，原因是什么？谢谢

### ISSUE THREAD

**Issue by vincentzhouwenqi** [sychaichangkun/ROS-Academy-for-Beginners#60]
vincent@vincent-PC: ~$ cd ~/catkin_ws
vincent@vincent-PC: ~/catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
robot_sim_demo: No definition of [yocs_cmd_vel_mux] for OS version [bionic]
navigation_sim_demo: No definition of [dwa_local_planner] for OS version [bionic]
slam_sim_demo: No definition of [hector_mapping] for OS version [bionic]

**Comment by sktzhaoshilipenzi** [comment]
你都知道版本是melodic安装命令还用kinetic

**Comment by vincentzhouwenqi** [comment]
vincent@vincent-PC:~/catkin_ws/src$ cd ~/catkin_ws
vincent@vincent-PC:~/catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro=melodic -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
robot_sim_demo: Cannot locate rosdep definition for [yocs_cmd_vel_mux]
navigation_sim_demo: Cannot locate rosdep definition for [gmapping]
slam_sim_demo: Cannot locate rosdep definition for [hector_mapping]
改成melodic之后仍存在该问题

**Comment by sktzhaoshilipenzi** [comment]
https://blog.csdn.net/qq_32115419/article/details/81585942

**Comment by sktzhaoshilipenzi** [comment]
感觉就是新版本缺包
