### ISSUE TITLE
关于gazebo建模问题

### ISSUE THREAD

**Issue by ROSstudy** [sychaichangkun/ROS-Academy-for-Beginners#61]
柴老师，您好，十分感谢您的课程，我在这堂课里学到了许多。我的课程恰巧也是一个关于轮式机器人的控制设计，您的课程让我受益良多。
       现在我想在gazebo里建立一个场景的模型，期待的最终效果就像您在例程里面所构建的博物馆那样。但是我试了试gazebo里面自带的建模工具，总是达不到您的那种逼真的效果。在这里想问问您是用什么工具构建的场景，具体的操作步骤又是什么。希望能得到您的指点。
      您的课程为我打开了ros学习的大门，可当我想再进一步的时候却被目前各式各样的教程迷乱了双眼，不知您有没有再开课程的计划能更详细的讲解ros的开发。我也恰巧是一名北京的学生，如果有线下的课程我也希望能前来学习。
     最后，再次感谢您，希望能得到您的回复

**Comment by sychaichangkun** [comment]
你好，Gazebo模型我们是用3d max建出来的，导出dae格式。 
Gazebo官方推荐用Blender建模，这个软件是开源免费的，可以在linux上运行，功能和3dmax差不多。
具体的建模、贴图、渲染你可以网上找些资料看。

重德智能目前开发了一门更为详细的机器人开发课程，可以在论坛里可以查看详情
https://q.droid.ac.cn/
有什么问题你也可以在论坛里提问
