### ISSUE TITLE
confusing code: q.setRPY(yaw,pitch,roll);

### ISSUE THREAD

**Issue by fridayfang** [sychaichangkun/ROS-Academy-for-Beginners#71]
I found confusing code in  `ROS-Academy-for-Beginners/tf_demo/src/coordinate_transformation.cpp`:

`q.setRPY(yaw,pitch,roll);`

But it should be set by sequence `roll,pitch,yaw`

**Comment by anchuanxu** [comment]
Hi, welcome to ask your question, this question is because in our code we use the Frame of OPENGL, in which the order is yaw,pitch,roll.

**Comment by sun0912704** [comment]
thank you. l will learn it three weeks later.&nbsp;



---Original---

**Comment by anchuanxu** [comment]
> thank you. l will learn it three weeks later.&nbsp;
> […](#)
> ---Original--- From: "anchuanxu"<notifications@github.com&gt; Date: Mon, Jun 15, 2020 21:46 PM To: "sychaichangkun/ROS-Academy-for-Beginners"<ROS-Academy-for-Beginners@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: Re: [sychaichangkun/ROS-Academy-for-Beginners] confusing code: q.setRPY(yaw,pitch,roll); (#71) Hi, welcome to ask your question, this question is because in our code we use the Frame of OPENGL, in which the order is yaw,pitch,roll. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

you are welcome! Welcome to exchange more ros questions

**Comment by anchuanxu** [comment]
> > thank you. l will learn it three weeks later. 
> > […](#)
> > ---Original--- From: "anchuanxu"<[notifications@github.com](mailto:notifications@github.com)> Date: Mon, Jun 15, 2020 21:46 PM To: "sychaichangkun/ROS-Academy-for-Beginners"<[ROS-Academy-for-Beginners@noreply.github.com](mailto:ROS-Academy-for-Beginners@noreply.github.com)>; Cc: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; Subject: Re: [sychaichangkun/ROS-Academy-for-Beginners] confusing code: q.setRPY(yaw,pitch,roll); (#71) Hi, welcome to ask your question, this question is because in our code we use the Frame of OPENGL, in which the order is yaw,pitch,roll. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> you are welcome! Welcome to exchange more ros questions

Sorry, I checked the documentation and found that the correct order of this function call is indeed roll pitch yaw, which caused us to code irregularities. Thank you for pointing out that we will correct it in subsequent versions.   
http://docs.ros.org/jade/api/tf/html/c++/classtf_1_1Quaternion.html#ab34dfef6a01c1ece07bea92d485b0576

**Comment by fridayfang** [comment]
thanks for your response!!
